name: main
on: [push]

jobs:

  build-and-test-node14:
    runs-on: ubuntu-20.04
    name: Testing dengan Github
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      - uses: bahmutov/npm-install@v1
      - run: npm run --prefix cypress/integration
      - uses: cypress-io/github-action@v2
        with:
          browser: chrome